# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Venky(91eabd65-5cb3-4a20-8940-79616b13cd00)'
    subscriptionId: '91eabd65-5cb3-4a20-8940-79616b13cd00'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
